# This notebook containes Pytorch very basic operations needed in day2day ML, these are very few of many such operations
 
### Two Steps: 
    - Acquire data
    - Process Data
### N-Dimensiona array:
    - Also knonw as `tensors`.
    - In Deep learning frameworks, the tensor class (ndarray in MXNet, Tensor in PyTorch and TensorFlow) resembles 
     `NumPy’s ndarray`
    
    ** Tensor class **
        - Supports auto differentiation.
        - Feverages GPUs
        - A tensor represents a (possibly multidimensional) array of numerical values.
        
        ** Vector **
        -  When only one axis is needed for the data, a tensor is called a **vector**.
        -  When two axes are needed for the data, a tensor is called a **matrix**.
        -  For, d>2 we call k<sup>th</sup>-order tensor.

In [1]:
#pytorch tensors

import torch # import for pytorch
x = torch.arange(12, dtype=torch.float32) # arange(n), create a vector of evenly spaced values, starting at 0 (included) and ending at n (not included). Default interval size is 1. 
print(x.shape) #gives shape of tensor
print(x.numel()) #give total number of elements in a tensor 
X_reshape=x.reshape(3,4) #reshape the x 
print(X_reshape.numel())
zero_tensor=torch.zeros((2, 3, 4)) #tensor with all elements= 0 and shape= (2, 3, 4) 
one_tensor=torch.ones((2, 3, 4)) #tensor with all elements= 1 and shape= (2, 3, 4) 

# Creates a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1.
rand_tensor=torch.randn(3, 4) 
normal_tensor= torch.tensor([[2, 1, 4, 3], [1, 33, 1, 5]])

torch.Size([12])
12
12


In [5]:
#slicing in tensors x[i,j] => i(included), j(does not include)
x[-1] #selects the last row 
x[1:3] #selects the second and third rows.
X_reshape[0, 1] = 111 #write element to (0,1)
X_reshape

tensor([[  0., 111.,   2.,   3.],
        [  4.,   5.,   6.,   7.],
        [  8.,   9.,  10.,  11.]])

In [6]:
#operations in tensors
x = torch.tensor([-1.0, 3, 5, 7])
y = torch.tensor([1, -1, 7, 3])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 0.,  2., 12., 10.]),
 tensor([-2.,  4., -2.,  4.]),
 tensor([-1., -3., 35., 21.]),
 tensor([-1.0000, -3.0000,  0.7143,  2.3333]),
 tensor([-1.0000e+00,  3.3333e-01,  7.8125e+04,  3.4300e+02]))

In [9]:
'''
Concatenate multiple tensors by stacking them end-to-end to form a larger one
Steps:
    provide a list of tensors 
    provide axis along which to concatenate
'''
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[-3.0, 1, 5, 3], [1, 7, 5, 11], [1, 13, 7, 3]])
torch.cat((X, Y), dim=0)
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3., -3.,  1.,  5.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  7.,  5., 11.],
        [ 8.,  9., 10., 11.,  1., 13.,  7.,  3.]])

In [10]:
#Numpy to tensor 
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [11]:
#Saving Memory with Python’s id() function : gives us the exact address of the referenced object in memory
before = id(X_reshape)
X_reshape = X_reshape + torch.ones(3,4)
id(X_reshape) == before

False